### ISSUE TITLE
create rpm?

### ISSUE THREAD

**Issue by cookie33** [EUDAT-DPMT/eudat.accounting.server#3]
Hi,

Is it possible to create an rpm as follows: `python setup.py bdist_rpm`?

If it is possible can this be added to the readme file?

**Comment by raphael-ritz** [comment]
Do you want this for the client or the server? So far, I didn't consider to properly publish the server implementation. Would you have use for this?

**Comment by cookie33** [comment]
HI,

I did it with the client and it just works. And that's only what we are interested in.

It could just be added to the README.md

just my 2 cents.

**Comment by cookie33** [comment]
And I missed out. I should have opened this on the client. My bad.

Sorry. This can be closed..
